In [3]:
import numpy as np

In [4]:
from time import process_time

In [10]:
pd.set_option('display.precision', 7)

In [8]:
import pandas as pd

In [12]:
list1 = [1,2,3,4]
print(list1)
type(list1)

[1, 2, 3, 4]


list

In [17]:
np_array = np.array([1,2,3,4])
print(np_array)
print(np_array.shape)
type(np_array)

[1 2 3 4]
(4,)


numpy.ndarray

In [19]:
nparr1 = np.array([(1,2,3,4),(5,6,7,8)])
print(nparr1)
print(nparr1.shape)
type(nparr1)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


numpy.ndarray

In [20]:
nparr2 = np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(nparr2)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


In [24]:
# create a numpy array of Zeroes
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [25]:
y = np.ones((4,5))
print(y)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [26]:
z = np.full((4,5),5)
print(z)

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]


In [29]:
w = np.eye(4)
print(w)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [30]:
# create a numpy array with random values
a = np.random.random((4,5))
print(a)

[[0.15303374 0.14687862 0.42553985 0.38939424 0.72705991]
 [0.12330089 0.00259038 0.85672109 0.23047075 0.70129141]
 [0.46666305 0.25736898 0.15050265 0.72401735 0.69307136]
 [0.28264426 0.823015   0.82377475 0.12035674 0.28142404]]


In [32]:
b = np.random.randint(10,100,(4,5))
print(b)

[[67 91 11 98 67]
 [65 80 65 64 35]
 [48 35 66 23 66]
 [16 73 42 73 44]]


In [33]:
# array of evenly spaced values --> specifying the number of values required
c = np.linspace(10,30,6)
print(c)

[10. 14. 18. 22. 26. 30.]


In [34]:
# array of evenly spaced values --> specifying the step
d = np.arange(10,30,6)
print(d)

[10 16 22 28]


In [35]:
list1 = [1,2,3,4]
nparr3 = np.array(list1)
print(nparr3)
print(type(nparr3))
print(nparr3.shape)

[1 2 3 4]
<class 'numpy.ndarray'>
(4,)


In [38]:
e = np.random.randint(10,90,(4,5))
print(e)

[[50 72 21 27 33]
 [18 28 83 55 37]
 [57 55 31 12 55]
 [82 44 35 16 58]]


In [39]:
# array dimension
e.shape
# no of dimension
e.ndim
# no of element
e.size
# data type
e.dtype

dtype('int32')

In [40]:
nparr4 = np.random.randint(0,10,(3,3))
nparr5 = np.random.randint(10,20,(3,3))

print(nparr4+nparr5)
print(nparr5-nparr4)
print(nparr5/nparr4)
print(nparr5*nparr4)

[[26 22 25]
 [17 21 17]
 [21 21 16]]
[[10  6 13]
 [ 3 15 11]
 [13 11 12]]
[[2.25       1.75       3.16666667]
 [1.42857143 6.         4.66666667]
 [4.25       3.2        7.        ]]
[[144 112 114]
 [ 70  54  42]
 [ 68  80  28]]


In [44]:
print(np.add(nparr4,nparr5))
print(np.subtract(nparr5,nparr4))
print(np.divide(nparr5,nparr4))
print(np.multiply(nparr5,nparr4))

[[26 22 25]
 [17 21 17]
 [21 21 16]]
[[10  6 13]
 [ 3 15 11]
 [13 11 12]]
[[2.25       1.75       3.16666667]
 [1.42857143 6.         4.66666667]
 [4.25       3.2        7.        ]]
[[144 112 114]
 [ 70  54  42]
 [ 68  80  28]]


In [47]:
nparr6 = np.random.randint(10,20,(4,3))
print(nparr6)
# transpose of matrix

arr = np.transpose(nparr6)
print(arr)
print(arr.shape)

# another way to find

arr1 = nparr6.T
print(arr1)
print(arr1.shape)

[[18 19 11]
 [18 12 18]
 [14 16 18]
 [14 16 13]]
[[18 18 14 14]
 [19 12 16 16]
 [11 18 18 13]]
(3, 4)
[[18 18 14 14]
 [19 12 16 16]
 [11 18 18 13]]
(3, 4)


In [53]:
# reshaping an array

nparr7 = np.random.randint(0,10,(2,3))
nparr8 = nparr7.reshape(3,2) 
print(nparr7)   
print(nparr8)

[[5 1 1]
 [4 0 0]]
[[5 1]
 [1 4]
 [0 0]]
